services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    user: "13001:13001"
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ${DATA_PATH}:/data
    command: >
      start -A --log debug --user root --pass ${PASSWD} file:/data
    networks:
      - mydr24-network

networks:
  mydr24-network:
    external: true