services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - surreal-data:/data
    command: >
      start -A --user root --pass ${PASSWD} file:///data
    networks:
      - mydr24-network

volumes:
  surreal-data:
    driver: local

networks:
  mydr24-network:
    external: true