services:
  surrealdb:
    # Build from our custom Dockerfile to ensure correct permissions
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # run as root inside container to avoid /data permission issues
    # do not set a non-root user here
    ports:
      - "${DB_PORT:-8800}:8000"
    volumes:
      - ${DB_PATH:-surreal_data}:/data
    command: >
      start -A --user ${DB_USER:-root} --pass ${DB_PASSWD:-root} rocksdb:///data
    networks:
      - ${NETWORK_NAME:-data-network}

volumes:
  surreal_data:
    driver: local

networks:
  ${NETWORK_NAME:-data-network}:
    driver: bridge
    external: ${NETWORK_EXTERNAL:-false}
