services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    user: "13001:13001"
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ${DATA_PATH:-surrealdb_data}:/data
    command: >
      start --log debug --user root --pass ${PASSWD}
      rocksdb:///data/database.db
    networks:
      - mydr24-network

networks:
  mydr24-network:
    external: true

volumes:
  surrealdb_data:
    driver: local