services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "${DB_PORT:-4800}:8000"
    volumes:
      - ${DB_PATH}:/data
    command: >
      start -A --user ${DB_USER} --pass ${DB_PASSWD} file:///data
    networks:
      - mydr24-network

volumes:
  surreal-data:
    driver: local

networks:
  mydr24-network:
    external: true
